### ISSUE TITLE
Error during connection 

### ISSUE THREAD

**Issue by mjcumming** [seime/openhab-esphome#26]
I see this error occasionally in the logs. I cannot reliably reproduce it. Using OH 4.2 with latest binding from the marketplace.

`2024-07-23 09:39:12.689 [WARN ] [home.internal.handler.ESPHomeHandler] - [363e94a024] Error initial connection
no.seime.openhab.binding.esphome.internal.comm.ProtocolAPIError: Failed to connect to '192.168.5.173' port 6053
	at no.seime.openhab.binding.esphome.internal.comm.ESPHomeConnection.connect(ESPHomeConnection.java:63) ~[?:?]
	at no.seime.openhab.binding.esphome.internal.comm.PlainTextFrameHelper.connect(PlainTextFrameHelper.java:37) ~[?:?]
	at no.seime.openhab.binding.esphome.internal.handler.ESPHomeHandler.connect(ESPHomeHandler.java:179) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:579) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:586) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:853) ~[?:?]
	at java.nio.channels.SocketChannel.open(SocketChannel.java:285) ~[?:?]
	at no.seime.openhab.binding.esphome.internal.comm.ESPHomeConnection.connect(ESPHomeConnection.java:54) ~[?:?]
	... 8 more`

**Comment by seime** [comment]
It says "No route to host". 

You seem to have some network instabilities?

**Comment by mjcumming** [comment]
I have been testing using this library https://github.com/peterkeen/aioesphomeserver/tree/bcc3ccd06eddcae6b469ec7ffd2ffc7d56bd53d2 to create ESPHome devices using python (PI application for me). So the errors happen when restarting the server(device) I am working on.

**Comment by seime** [comment]
Hard to tell why the jvm cannot connect, but this does not seem like a binding specific problem, but that your pi isnt available on the network.

The binding tries to reconnect after 40 secs.

**Comment by mjcumming** [comment]
Agree, the problem is on the pi side - not sure if you want to handle the error more gracefully?

**Comment by seime** [comment]
I could, but it would either require a more cluttered codebase - or it would make it harder for me to understand the issue report 😅
